@startuml
title Process Design Class Diagram
package fast::rf::BlahSystem::BlahSubsystem #LightYellow;line:blue {
  abstract IBlahNameProcess
  note right of IBlahNameProcess
    An interface class for a Process.
    - Should contain NO implementation.
  end note
  abstract BaseBlahNameProcess
  BaseBlahNameProcess .up.|> IBlahNameProcess
  note right of BaseBlahNameProcess
    An abstract class for a Process.
    - Should contain all COMMON implementation
  end note
  class BasicBlahNameProcess
  BasicBlahNameProcess -up-|> BaseBlahNameProcess
  note bottom of BasicBlahNameProcess
    A trivial concrete implementation of the Process
  end note
  class DummyBlahNameProcess
  DummyBlahNameProcess -up-|> BaseBlahNameProcess
  note bottom of DummyBlahNameProcess
    A concrete implementation of the Process
    - Provides dummy data useful for testing and validation
    - Minimal dependency on other systems/subsystems/processes (NOT ZERO)
  end note
  class OtherBlahNameProcess
  OtherBlahNameProcess -up-|> BaseBlahNameProcess
  note bottom of OtherBlahNameProcess
    Other concrete implementation's of the Process.
    - May be may of these.
  end note
}
@enduml