@startuml
title Controller Class Diagram
namespace fast::rf {
  namespace NavigationSystem  {
    package Controller #LightYellow;line:blue {
        enum ControllerType #LimeGreen {
            UNKNOWN=0,
            PID_CONTROLLER=1,
            END_OF_LIST=2
        }
        interface IControllerOutput #Yellow {

        }
        interface IControllerConfig #Orange {

        }
        interface IController #LimeGreen {
            +{abstract} bool init(IControllerConfig config)
            +{abstract} bool new_set_point(double set_point,double time_stamp_sec)
            +{abstract} bool new_sensor_input(double sensor_input,double time_stamp_sec)
            +{abstract} bool update(double current_time_sec)
            +{abstract} double get_sensor_delta_time_sec()
            +{abstract} bool get_output(IControllerOutput output)
            +{abstract} string pretty()

        }
        IController +-- ControllerType
        IController --> IControllerOutput: <<use>>
        IController --> IControllerConfig: <<use>>
        abstract BaseController #LimeGreen {
            +ControllerType get_controller_type()
            +double get_sensor_delta_time_sec()
            #bool init(IControllerConfig config)
            #bool new_set_point(double set_point,double time_stamp_sec)
            #bool new_sensor_input(double sensor_input,double time_stamp_sec)
            #bool update(double current_time_sec)
            #string pretty()
            #IControllerConfig config_
            -ControllerType controller_type
        }
        BaseController .up.|> IController
        class PIDControllerOutput #Orange {

        }
        PIDControllerOutput -up-|> IControllerOutput
        class PIDControllerConfig #Orange {

        }
        PIDControllerConfig -up-|> IControllerConfig
        class PIDController #Orange {
            +bool init(PIDControllerConfig config)
            +bool new_set_point(double set_point,double time_stamp_sec)
            +bool new_sensor_input(double sensor_input,double time_stamp_sec)
            +bool update(double current_time_sec)
            +bool get_output(PIDControllerOutput output)
            +string pretty()
        }
        PIDController -up-|> BaseController
        PIDController --> PIDControllerOutput: <<use>>
        PIDController --> PIDControllerConfig: <<use>>
    }
  }
}
@enduml