@startuml
title PID Auto Tuner Class Diagram
namespace fast::rf {
  namespace NavigationSystem  {
    namespace Controller {
        enum ControllerType #LimeGreen {
            UNKNOWN=0,
            PID_CONTROLLER=1,
            RELAY_AUTO_TUNE_CONTROLLER=2,
            PID_AUTO_TUNER=3,
            END_OF_LIST=4
        }
       
        interface IControllerOutput #LimeGreen {
            +bool is_new
            +double command_value
        }
        interface IControllerConfig #LimeGreen {
            +{abstract} bool is_ok()
            +{abstract} string pretty()
            +double get_max_output()
            +double get_min_output()
            #double max_output
            #double min_output
           


        }
        interface IController #LimeGreen {
            +{abstract} ~IController()
            +{abstract} ControllerType get_controller_type()
            +{abstract} bool init()
            +{abstract} bool new_set_point(double set_point,double time_stamp_sec)
            +{abstract} bool new_sensor_input(double sensor_input,double time_stamp_sec)
            +{abstract} bool update(double current_time_sec)
            +{abstract} double get_sensor_delta_time_sec()
            +{abstract} IControllerOutput* get_output()
            +{abstract} string pretty()
            +{abstract} bool clear()
        }
        IController +-- ControllerType
        IController --> IControllerOutput: <<use>>
        abstract BaseController #LimeGreen {
            +ControllerType get_controller_type()
            +double get_sensor_delta_time_sec()
            #bool init()
            #bool new_set_point(double set_point,double time_stamp_sec)
            #bool new_sensor_input(double sensor_input,double time_stamp_sec)
            #bool update(double current_time_sec)
            #string pretty()
            -ControllerType controller_type
        }
        BaseController .up.|> IController
        class PIDControllerOutput #LimeGreen {
            +double setpoint_sensor_error
            +double P_term
            +double I_term
            +double D_term
        }
        PIDControllerOutput -up-|> IControllerOutput
        class PIDControllerConfig #LimeGreen {
            +void set_parameters(double max_value, double min_value, double P, double I, double D, double sensor_scale_factor)
            +bool is_ok()
            +string pretty()
            +double get_K_P()
            +double get_K_I()
            +double get_K_D()
            +double get_sensor_scale()
            -double K_P
            -double K_I
            -double K_D
            -double sensor_scale
            -double dead_time_sec
            -double lambda_sec
            
            

        }
        PIDControllerConfig -up-|> IControllerConfig
        class PIDController #LimeGreen {
            +bool init()
            +bool set_config(PIDControllerConfig config)
            +bool new_set_point(double set_point,double time_stamp_sec)
            +bool new_sensor_input(double sensor_input,double time_stamp_sec)
            +bool update(double current_time_sec)
            +PIDControllerOutput* get_output()
            +string pretty()
            +bool clear()
            -PIDControllerConfig config
        }
        PIDController -up-|> BaseController
        PIDController --> PIDControllerOutput: <<use>>
        PIDController --> PIDControllerConfig: <<use>>

    }
    package ControllerTuner #LightYellow;line:blue {
        enum AutoTunerState #Yellow {
            IDLE,
            TUNING,
            COMPLETE,
            FAILED
        }

        enum PIDAutoTunerAlgorithmState #Yellow {
            IDLE,
            CAPTURE_BASELINE,
            APPLY_STEP,
            MEASURE_RESPONSE,
            EVALUATE_PID,
            COMPLETE,
            FAILED
        }

        enum PIDAutoTunerFailureReason #Yellow {
            NONE
            INVALID_CONFIGURATION
            RESPONSE_TIMEOUT
            INSUFFICIENT_RESPONSE
            TRACKING_ERROR_EXCEEDED
            TUNING_ITERATION_LIMIT
            UNSUPPORTED_ALGORITHM
        }

        enum PIDAutoTuningAlgorithm #Yellow {
            STEP_RESPONSE
            ' RELAY_FEEDBACK
            IMC_LAMBDA
            ' ZIEGLER_NICHOLS_STEP_RESPONSE
            ' ZIEGLER_NICHOLS_ULTIMATE_GAIN
            ' COHEN_COON
        }

        class PIDAutoTunerConfig #Yellow {
            +void set_parameters(double max_output, double min_output, double P, double I, double D, double sensor_scale_factor)
            +void set_tuning_parameters(double output_step, double set_point_step, double settle_time_sec, double response_timeout_sec, double minimum_response, double acceptable_error_threshold, double evaluation_time_sec, size_t max_tuning_iterations)
            +void set_algorithm(PIDAutoTuningAlgorithm algorithm)
            +void set_imc_parameters(double dead_time_sec, double lambda_sec)
            +bool is_ok()
            +string pretty()
            +double get_K_P()
            +double get_K_I()
            +double get_K_D()
            +double get_sensor_scale()
            +double get_output_step()
            +double get_set_point_step()
            +double get_settle_time_sec()
            +double get_response_timeout_sec()
            +double get_minimum_response()
            +double get_acceptable_error_threshold()
            +double get_evaluation_time_sec()
            +size_t get_max_tuning_iterations()
            +PIDAutoTuningAlgorithm get_algorithm()
            +double get_dead_time_sec()
            +double get_lambda_sec()
            -bool parameters_set
            -bool tuning_parameters_set
            -double K_P
            -double K_I
            -double K_D
            -double sensor_scale
        }
        PIDAutoTunerConfig -up-|> IControllerConfig
        class PIDAutoTunerOutput #Yellow {
            +AutoTunerState state
            +PIDAutoTuningAlgorithm algorithm
            +PIDAutoTunerFailureReason failure_reason
            +string failure_reason_string
            +string failure_attribute
            +string failure_remediation
            +PIDAutoTunerAlgorithmState algorithm_state
            +double set_point
            +double sensor_input
            +double K_P
            +double K_I
            +double K_D
            +double response
            +double tracking_error
            +double maximum_tracking_error
            +double elapsed_time_sec
        }
        PIDAutoTunerOutput -up-|> IControllerOutput
        PIDAutoTunerOutput *-> AutoTunerState
        PIDAutoTunerOutput *-> PIDAutoTunerAlgorithmState
        PIDAutoTunerOutput *-> PIDAutoTuningAlgorithm
        class PIDAutoTuner #Yellow {
            +bool init()
            +ControllerType get_controller_type()
            +bool start_tuning()
            +bool set_config(PIDAutoTunerConfig config)
            +bool new_set_point(double set_point,double time_stamp_sec)
            +bool new_sensor_input(double sensor_input,double time_stamp_sec)
            +bool update(double current_time_sec)
            +PIDAutoTunerOutput* get_output()
            +string pretty()
            +bool clear()
            +bool is_tuning_complete()
            +bool tuning_succeeded()
            +PIDControllerConfig get_tuned_config()
            +AutoTunerState get_state()
            +PIDAutoTunerAlgorithmState get_algorithm_state()
            -bool run_tuning_step(double current_time_sec)
            -PIDAutoTunerConfig config
        }
        PIDAutoTuner +-- AutoTunerState
        PIDAutoTuner -up-|> BaseController
        PIDAutoTuner *-down-> PIDAutoTunerConfig
        PIDAutoTuner *-down-> PIDAutoTunerOutput
        PIDAutoTuner --> PIDAutoTunerAlgorithmState: <<use>>

    }
    
  }
}
@enduml
