@startuml
title System-Navigation Package Diagram

namespace fast::rf {
  namespace messages  {}
  namespace NavigationSystem {
    interface INavigationSystem {
    }
    abstract BaseNavigationSystem {
    }
    INavigationSystem <|-- BaseNavigationSystem
    class BasicNavigationSystem {

    }
    BaseNavigationSystem <|-- BasicNavigationSystem
    class DummyNavigationSystem  {
    }
    BaseNavigationSystem <|-- DummyNavigationSystem
    package GlobalPlannerSubsystem {

    }
    package LocalPlannerSubsystem {

    }
    package NavigationExecutor {
      
    }
  }
}
@enduml