@startuml
title System-Navigation Package Diagram

namespace fast::rf {
  package NavigationSystem #LightYellow;line:blue {
    interface INavigationSystem {
    }
    abstract BaseNavigationSystem {
    }
    INavigationSystem <|-- BaseNavigationSystem
    class BasicNavigationSystem {

    }
    BaseNavigationSystem <|-- BasicNavigationSystem
    class DummyNavigationSystem  {
    }
    BaseNavigationSystem <|-- DummyNavigationSystem
    namespace GlobalPlannerSubsystem {
      namespace GlobalPlannerManagerProcess {
        interface IGlobalPlannerManagerProcess
      }
      namespace GlobalPathStorageProcess {
        interface IGlobalPathStorageProcess
      }
      namespace FreeSpacePlannerProcess {
        interface IFreeSpacePlannerProcess
      }
      namespace GlobalPathRoutePlannerProcess {
        interface IGlobalPathRoutePlannerProcess
      }
    }
    namespace Controller {
      interface IController #LimeGreen {}
      class PIDController #LimeGreen {}
      PIDController -up-|> IController
    }
    namespace LocalPlannerSubsystem {

    }
    namespace NavigationExecutorSubsystem {
      interface IDriveExecutorProcess #LimeGreen
      class TankDriveExecutorProcess #LimeGreen
      TankDriveExecutorProcess -up-|> IDriveExecutorProcess
      interface ITrajectoryControllerProcess
      interface ITrajectorySelectorProcess
    }
  }
}
@enduml