' @compare_tag Process-ClassDiagram v0.1
@startuml
title IMU Process Class Diagram

namespace fast::rf {
  namespace DiagnosticDefinition {
    enum DiagnosticType
  }
  namespace messages {
    namespace InfrastructureMsgs {
      class DiagnosticMsg <<(M,#FFFF00)>>
      class ReadyToArmStatusMsg <<(M,#FFFF00)>>
    }
    namespace SensorMsgs {
      class ImuMsg <<(M,#FFFF00)>>
      class MagneticFieldMsg <<(M,#FFFF00)>>
    }
    namespace StandardMsgs {
      class Covariance3DMsg <<(M,#FFFF00)>>
    }
  }
  namespace core::Infrastructure {
    class DiagnosticManager
  }
  interface IProcess
  namespace PoseSystem {
    package InertialSensorSubsystem #LightYellow;line:blue {
        interface IIMUProcess #LimeGreen {
          +{abstract} bool init(IMUDevice imu_type,string imu_device_name)
          +{abstract} bool get_imu_data(ImuMsg& data)
          +{abstract} bool get_magnetic_data(MagneticFieldMsg& data)
          +{abstract} double get_packet_dropped_rate()
          +{abstract} double get_packet_rx_rate()
        }
        IIMUProcess -up-|> IProcess
        IIMUProcess --> IMUDevice: <<use>>
        
        abstract BaseIMUProcess #LimeGreen {
          +DiagnosticMsg[] getDiagnostics()
          +bool updateDiagnostic(DiagnosticType type, Level level, DiagnosticMessage message, string description)
          +ReadyToArmStatusMsg get_ready_to_arm()
          #bool update(double current_time_sec)
          #string pretty()
          #DiagnosticManager diagnosticManager
          #ReadyToArmStatusMsg ready_to_arm
          -IIMUDriver driver

        }
        BaseIMUProcess .up.|> IIMUProcess
        BaseIMUProcess --> DiagnosticManager: <<use>>

        enum IMUDevice #LimeGreen {
          UNKNOWN=0,
          MOCK_IMU=1,
          SYDTM151_IMU=2
          RAZOR9DOF_IMU = 3,
          END_OF_LIST=4,
        }
        interface IIMUDriver #LimeGreen {
          +{abstract} bool init(string imu_device_name)
          +{abstract} string pretty()
          +{abstract} update(double current_time_sec)
          +{abstract}  bool get_imu_data(ImuMsg& data)
          +{abstract} bool get_magnetic_data(MagneticFieldMsg& data)
          +{static} IMUDevice convert_name(std::string name);
          +{abstract} double get_packet_dropped_rate()
          +{abstract} double get_packet_rx_rate()
        }
        IIMUDriver +-- IMUDevice
        struct SensorData #LimeGreen {
          +ImuMsg imu_msg
          +MagneticFieldMsg magnetic_field_msg
        }
        struct DataPacket #LimeGreen {
            +bool ok
            +bool skipped
            +uint8 packet_type
            +double acc_x_g
            +double acc_y_g
            +double acc_z_g
            +double gyro_x_rps
            +double gyro_y_rps
            +double gyro_z_rps
            +double mag_x_T
            +double mag_y_T
            +double mag_z_T
            +double pitch_rad
            +double roll_rad
            +double yaw_rad
            +double heading_rad
        }
        abstract BaseIMUDriver #LimeGreen {
          +bool get_imu_data(ImuMsg& data)
          +bool get_magnetic_data(MagneticFieldMsg& data)
          +double get_packet_dropped_rate()
          +double get_packet_rx_rate()
          #bool init(IMUConfig imu_config)
          #update(double current_time_sec)
          #string pretty()
          #void increment_packet_rx_counter()
          #uint64 get_packet_rx_counter()
          #void increment_packet_rx_dropped_counter()
          #ImuMsg imu_data
          #MagneticFieldMsg magnetic_data
        }
        BaseIMUDriver .up.|> IIMUDriver
        BaseIMUDriver +-- SensorData
        BaseIMUDriver +-- DataPacket

        class MockIMUDriver #LimeGreen {
           +bool init(string imu_device_name)
           +update(double current_time_sec)
           +string pretty()
           
        }
        MockIMUDriver -up-|> BaseIMUDriver

        class IMUSYDTM151Driver #LimeGreen {
           +bool init(string imu_device_name)
           +update(double current_time_sec)
           +string pretty()
        }
        IMUSYDTM151Driver -up-|> BaseIMUDriver
        class IMURazor9DOFDriver #LimeGreen {
           +bool init(string imu_device_name)
           +update(double current_time_sec)
           +string pretty()
        }
        IMURazor9DOFDriver -up-|> BaseIMUDriver
        class IMUProcess #LimeGreen {
          +bool init(IMUConfig imu_config)
          +bool update(double current_time_sec)
          +string pretty()
          +bool get_imu_data(ImuMsg& data)
          +bool get_magnetic_data(MagneticFieldMsg& data)
          
        }
        struct IMUConfig #Orange {
          IMUDevice device_type
          string imu_device_name
          Covariance3DMsg linear_accelerometer_covariance
          Covariance3DMsg gyro_covariance
          Covariance3DMsg magnetometer_covariance
          Covariance3DMsg orientation_covariance
        }
        IMUProcess +-- IMUConfig
        IMUProcess -up-|> BaseIMUProcess
        IMUProcess --> IIMUDriver
        class DummyIMUProcess {
          +bool init(IMUConfig imu_config)
          +bool update(double current_time_sec)
          +string pretty()
          +bool get_imu_data(ImuMsg& data)
          +bool get_magnetic_data(MagneticFieldMsg& data)
          #IMUConfig imu_config_
        }
        DummyIMUProcess -up-|> BaseIMUProcess
        DummyIMUProcess --> IIMUDriver
        DummyIMUProcess *-> MockIMUDriver
    }
  }
}
@enduml
