repos:
  - repo: local
    hooks:
      #- id: pre-commit-clang-tidy
      #  name: Run Clang Tidy for Changed Content
      #  entry: ./scripts/pre_commit/run_clangtidy.sh
      #  language: script
      #  verbose: true

      - id: pre-commit-check-template
        name: Check if code is up to date with templates
        entry: python scripts/update_from_template.py --templates templates/Process --impl Systems/ --dry-run
        pass_filenames: false
        language: system
        
      - id: pre-commit-code-format
        name: Code Formatting for Changed Files
        entry: ./scripts/pre_commit/format_code.sh
        language: script
      
      - id: pre-commit-generate-doxygen
        name: Generate Doxygen for All Files
        entry: ./scripts/pre_commit/generate_doxygen.sh
        language: script

      - id: pre-commit-plantuml-conversion
        name: Plantuml Conversion for Changed Files
        entry: ./scripts/pre_commit/plantuml_conversion.sh
        language: script

      - id: pre-commit-mermaid-conversion
        name: Mermaid Conversion for Changed Files
        entry: ./scripts/pre_commit/mermaid_conversion.sh
        language: script
        
      - id: pre-commit-dia-conversion
        name: Dia Conversion for Changed Files
        entry: ./scripts/pre_commit/dia_conversion.sh
        language: script

      - id: pre-commit-markdown-check
        name: Check Markdown for All Files
        entry: ./scripts/pre_commit/check_markdown.sh
        language: script