sonar.projectKey=fastrobotics_robot_framework
sonar.organization=fastrobotics
sonar.projectName=FAST Robot Framework
sonar.sources=Systems
sonar.tests=tests

# Tell SonarQube where to look for Cobertura XML coverage files
sonar.cfamily.cobertura.reportPaths=coverage.xml