@startuml
title DriveExecutor Process Class Diagram

namespace fast::fr {
  namespace messages {
    namespace GeometryMsgs {
      class TwistMsg <<(M,#FFFF00)>>
    }
  }
  namespace NavigationSystem {
    namespace NavigationExecutorSubsystem {
        interface IDriveExecutorOutput #LimeGreen {

        }
        interface IDriveExecutorProcess #LimeGreen {
          +{abstract} IDriveExecutorOutput new_cmd(TwistMsg cmd)
          +{abstract} bool update(double current_time_sec, double delta_time_sec)
        }
        IDriveExecutorProcess --> IDriveExecutorOutput: <<use>>
        abstract BaseDriveExecutorProcess #LimeGreen {
          +bool base_update(double current_time_sec, double delta_time_sec)

        }
        BaseDriveExecutorProcess -up-|> IDriveExecutorProcess
        class BasicDriveExecutorProcess {
          +bool update(double current_time_sec, double delta_time_sec)
        }
        BasicDriveExecutorProcess -up-|> BaseDriveExecutorProcess
        BasicDriveExecutorProcess --> IDriveExecutorOutput: <<use>>
        class DummyDriveExecutorProcess {
          +bool update(double current_time_sec, double delta_time_sec)
        }
        DummyDriveExecutorProcess -up-|> BaseDriveExecutorProcess
        DummyDriveExecutorProcess --> IDriveExecutorOutput: <<use>>
        class TankDriveExecutorProcessor #LimeGreen
        TankDriveExecutorProcessor -up-|> BaseDriveExecutorProcess
        TankDriveExecutorProcessor --> IDriveExecutorOutput: <<use>>
    }
  }
}
@enduml