@startuml
title DriveExecutor Process Class Diagram

namespace fast::fr {
  namespace DiagnosticDefinition {
    enum DiagnosticType
  }
  namespace messages {
    namespace InfrastructureMsgs {
      class DiagnosticMsg <<(M,#FFFF00)>>
    }
    namespace GeometryMsgs {
      class TwistMsg <<(M,#FFFF00)>>
    }
  }
  namespace core::Infrastructure {
    class DiagnosticManager
  }
  namespace NavigationSystem {
    namespace NavigationExecutorSubsystem {
        interface IDriveExecutorOutput #LimeGreen {

        }
        interface IDriveExecutorProcess #Orange {
          +{abstract} bool init()
          +{abstract} DiagnosticMsg[] get_diagnostics()
          +{abstract} IDriveExecutorOutput new_cmd(TwistMsg cmd)
          +{abstract} IDriveExecutorOutput get_output()
          +{abstract} bool update(double current_time_sec, double delta_time_sec)
          +{abstract} string pretty()
        }
        IDriveExecutorProcess --> IDriveExecutorOutput: <<use>>
        abstract BaseDriveExecutorProcess #Orange {
          +DiagnosticMsg[] get_diagnostics()
          +bool base_update(double current_time_sec, double delta_time_sec)
          +string pretty()
          #DiagnosticManager diagnosticManager
          

        }
        BaseDriveExecutorProcess -up-|> IDriveExecutorProcess
        BaseDriveExecutorProcess --> DiagnosticManager: <<use>>
        class BasicDriveExecutorProcess {
          +bool init()
          +IDriveExecutorOutput get_output()
          +bool update(double current_time_sec, double delta_time_sec)
        }
        BasicDriveExecutorProcess -up-|> BaseDriveExecutorProcess
        BasicDriveExecutorProcess --> IDriveExecutorOutput: <<use>>
        class DummyDriveExecutorProcess {
          +bool update(double current_time_sec, double delta_time_sec)
        }
        DummyDriveExecutorProcess -up-|> BaseDriveExecutorProcess
        DummyDriveExecutorProcess --> IDriveExecutorOutput: <<use>>
    }
  }
}
@enduml