' @compare_tag Process-ClassDiagram v0.1
@startuml
title DriveExecutor Process Class Diagram

namespace fast::rf {
  namespace DiagnosticDefinition {
    enum DiagnosticType
  }
  namespace messages {
    namespace InfrastructureMsgs {
      class DiagnosticMsg <<(M,#FFFF00)>>
    }
    namespace GeometryMsgs {
      class TwistMsg <<(M,#FFFF00)>>
    }
  }
  namespace core::Infrastructure {
    class DiagnosticManager
    class ReadyToArmStatusMsg <<(M,#FFFF00)>>
  }
  interface IProcess
  namespace NavigationSystem {
    namespace NavigationExecutorSubsystem {
      package DriveExecutor #LightYellow;line:blue {
        interface IDriveExecutorOutput #LimeGreen {

        }
        interface IDriveExecutorProcess #LimeGreen {
          +{abstract} bool init()
          +{abstract} IDriveExecutorOutput new_cmd(TwistMsg cmd)
          +{abstract} IDriveExecutorOutput get_output()
        }
	IDriveExecutorProcess -up-|> IProcess
        IDriveExecutorProcess --> IDriveExecutorOutput: <<use>>
        abstract BaseDriveExecutorProcess #LimeGreen {
          +DiagnosticMsg[] getDiagnostics()
          +bool updateDiagnostic(DiagnosticType type, Level level, DiagnosticMessage message, string description)
          +ReadyToArmStatusMsg get_ready_to_arm()
          #bool update(double current_time_sec)
          #string pretty()
          #DiagnosticManager diagnosticManager
          #ReadyToArmStatusMsg ready_to_arm 

        }
        BaseDriveExecutorProcess .up.|> IDriveExecutorProcess
        BaseDriveExecutorProcess --> DiagnosticManager: <<use>>
        class BasicDriveExecutorProcess {
          +bool init()
          +IDriveExecutorOutput get_output()
          +string pretty()
          +bool update(double current_time_sec)
        }
        BasicDriveExecutorProcess -up-|> BaseDriveExecutorProcess
        BasicDriveExecutorProcess --> IDriveExecutorOutput: <<use>>
        class DummyDriveExecutorProcess {
          +bool update(double current_time_sec)
        }
        DummyDriveExecutorProcess -up-|> BaseDriveExecutorProcess
        DummyDriveExecutorProcess --> IDriveExecutorOutput: <<use>>
        class TankDriveExecutorProcess #LimeGreen
        TankDriveExecutorProcess -up-|> IDriveExecutorProcess
      }
    }
  }
}
@enduml
