@startuml
title Fast::RF Messages Package Diagram
namespace fast::rf {
  package AwarenessMsgs {}
  package GeometryMsgs {}
  package SensorMsgs {}
  package StandardMsgs {}
  package InfrastructureMsgs {}
  package NavMsgs {}

}
@enduml