set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_library(cpu_math_lib STATIC cpu_math.cpp)
if(ARCHITECTURE_JETSONNANO)
  add_library(gpu_math_lib STATIC gpu_math.cu)
  target_link_libraries(gpu_math_lib PRIVATE CUDA::cudart)
  set_target_properties(gpu_math_lib PROPERTIES LINKER_LANGUAGE CUDA)

endif()

add_executable(math_benchmark main.cpp)
if(ARCHITECTURE_JETSONNANO)
  target_link_libraries(math_benchmark PRIVATE cpu_math_lib gpu_math_lib)
else()
  target_link_libraries(math_benchmark PRIVATE cpu_math_lib)
endif()
install(TARGETS math_benchmark RUNTIME DESTINATION bin)
