@startuml
title Standard Message Package Diagram

namespace fast::rf::messages {
  namespace Standard  {
    struct Vector3DMsg <<(M,#FFFF00) >> #Orange {
      +double x
      +double y
      +double z
    }
    struct Covariance6DMsg <<(M,#FFFF00) >> #Orange {
      +double[36] covariance
    }
}
@enduml