@startuml
title System-BaseMachine Package Diagram

namespace fast::rf {
  package BaseMachineSystem #LightYellow;line:blue {
    interface IBaseMachineSystem {
    }
    abstract BaseBaseMachineSystem {
    }
    IBaseMachineSystem <|-- BaseBaseMachineSystem
    class BasicBaseMachineSystem {

    }
    BaseBaseMachineSystem <|-- BasicBaseMachineSystem
    class DummyBaseMachineSystem  {
    }
    BaseBaseMachineSystem <|-- DummyBaseMachineSystem
    namespace BaseMachineSubsystem #LimeGreen {
      interface IHatDriverProcess #LimeGreen
      class ServoHatDriverProcess #LimeGreen
      ServoHatDriverProcess -up-|> IHatDriverProcess
      class IServoHatDriver #LimeGreen
      class ServoDriver #LimeGreen
      ServoDriver -up-|> IServoHatDriver
      ServoHatDriverProcess --> IServoHatDriver: <<use>>
    }
  }
}
@enduml