' @compare_tag System-PackageDiagram v0.1
@startuml
title System-Perception Package Diagram

namespace fast::rf {
  namespace messages  {}
  package PerceptionSystem #LightYellow;line:blue {
  }
}
@enduml