@startuml
title LocalPose Subsystem Class Diagram
namespace fast::rf {
  namespace messages {
    namespace SensorMsgs {
      class ImuMsg <<(M,#FFFF00)>>
    }
    namespace GeometryMsgs {
      class OdomMsg <<(M,#FFFF00)>>
    }
  }
  namespace PoseSystem {
    package LocalPoseSubsystem #LightYellow;line:blue {
      interface ILocalPoseSubsystem {

      }
      abstract BaseLocalPoseSubsystem {

      }
      BaseLocalPoseSubsystem .up.|> ILocalPoseSubsystem
      class BasicLocalPoseSubsystem {
      }
      BasicLocalPoseSubsystem -up-|> BaseLocalPoseSubsystem
      class DummyLocalPoseSubsystem {
      }
      DummyLocalPoseSubsystem -up-|> BaseLocalPoseSubsystem
      namespace InertialSensorFuserProcess #Yellow {
        interface IInertialSensorFuserProcess #Yellow {}
        class BasicInertialSensorFuserProcess #Yellow {}
        BasicInertialSensorFuserProcess -up-|> IInertialSensorFuserProcess

      }
      namespace WheelOdometryFuserProcess {

      }
      namespace VisualOdometryFuserProcess {

      }
      namespace LocalPoseFuserProcess #Yellow {
        interface ILocalPoseFuserProcess #Yellow {}
        class BasicLocalPoseFuserProcess #Yellow {}
        BasicLocalPoseFuserProcess -up-|> ILocalPoseFuserProcess
      }

    }
  }
}
@enduml