add_executable(exec_servohat_driver exec_ServoHatDriver.cpp)
if(${CMAKE_HOST_SYSTEM_PROCESSOR} STREQUAL armv7l)
  target_link_libraries(exec_servohat_driver servoHatDriver logger)
else()
  target_link_libraries(exec_servohat_driver mockServoHatDriver logger)
endif()
install(TARGETS exec_servohat_driver RUNTIME DESTINATION bin)
