@startuml
title Nav Messages Package Diagram

namespace fast::rf::messages {
  namespace GeometryMsgs {
    class OdomMsg <<(M,#FFFF00)>>
  }
  namespace NavMsgs  {
    class GlobalPathRequest <<(M,#FFFF00)>> #Orange {
      +uint64_t path_uuid
      +OdomMsg start
      +OdomMsg[] pass_thru_points
      +OdomMsg end
      +bool ok()

    }
    enum GlobalPathPlanningStatusEnum #Orange
    {
      UNKNOWN=0,
      STARTING=1,
      PLANNING=2,
      COMPLETED=3,
      FAILED=4,
      END_OF_LIST=5

    }
    GlobalPathRequest --> OdomMsg: <<use>>
    class GlobalPathResponse <<(M,#FFFF00)>> #Orange {
      +uint64_t path_uuid
      +GlobalPathPlanningStatusEnum state
      +OdomMsg[] path_points
    }
    GlobalPathResponse --> OdomMsg: <<use>>
    GlobalPathResponse --> GlobalPathPlanningStatusEnum: <<use>>
    class GlobalPathPlanningStatus <<(M,#FFFF00)>> {
      +uint64_t path_uuid
      +GlobalPathPlanningStatusEnum state
    }
    GlobalPathPlanningStatus --> GlobalPathPlanningStatusEnum: <<use>>
  }
}
@enduml