@startuml
title Diagnostic Manager Class Diagram
namespace fast::rf {
    namespace DiagnosticDefinition {
        enum DiagnosticType
    }
    namespace messages {
        namespace InfrastructureMsgs {
            class DiagnosticMsg <<(M,#FFFF00)>>
        }
    }
    namespace core::Infrastructure {
        class DiagnosticManager #Orange {
            +bool initialize_diagnostics(DiagnosticType[] diagnostic_types)
            +bool is_initialized()
            +DiagnosticMsg[] get_diagnostics()
            -DiagnosticMsg[] diagnostics
            -uint8_t system_id
            -uint8_t subsystem_id
            -uint8_t process_id
        }
        DiagnosticManager --> DiagnosticMsg: <<use>>
        DiagnosticManager --> DiagnosticType: <<use>>
    }
}
@enduml