@startuml
title Diagnostic Manager Class Diagram
namespace fast::rf {
    enum Level
    namespace DiagnosticDefinition {
        enum DiagnosticType
        enum DiagnosticMessage
    }
    namespace messages {
        namespace InfrastructureMsgs {
            class DiagnosticMsg <<(M,#FFFF00)>>
        }
    }
    namespace core::Infrastructure {
        class DiagnosticManager #LimeGreen {
            +bool initializeDiagnostics(DiagnosticType[] diagnosticTypes)
            +bool updateDiagnostic(DiagnosticType type, Level level, DiagnosticMessage message, string description)
            +bool isInitialized()
            +DiagnosticMsg[] getDiagnostics()
            +DiagnosticMsg[] getDiagnostics(Level)
            -DiagnosticMsg[] diagnostics
            -uint8_t m_systemId
            -uint8_t m_subsystemId
            -uint8_t m_processId
        }
        DiagnosticManager --> DiagnosticMsg: <<use>>
        DiagnosticManager --> DiagnosticType: <<use>>
        DiagnosticManager --> DiagnosticMessage: <<use>>
        DiagnosticManager --> Level: <<use>>
    }
}
@enduml