@startuml
title Awareness Msgs Class Diagram

namespace fast::rf::messages {
  namespace GeometryMsgs {
    class OdomMsg <<(M,#FFFF00) >>
  }
  namespace AwarenessMsgs {
  
    class ObjectMsg <<(M,#FFFF00) >> {

    }
    ObjectMsg --> OdomMsg: <<use>>
    class ObjectsMsg <<(M,#FFFF00) >> {

    }
    ObjectsMsg --> ObjectMsg: <<use>>
    
  }
}
@enduml