@startuml
title NavigationExecutor Subsystem Class Diagram
namespace fast::rf {
  namespace messages {
  }
  namespace NavigationSystem {
    package NavigationExecutorSubsystem #LightYellow;line:blue {
      interface INavigationExecutorSubsystem {

      }
      abstract BaseNavigationExecutorSubsystem {

      }
      BaseNavigationExecutorSubsystem .up.|> INavigationExecutorSubsystem
      class BasicNavigationExecutorSubsystem {
      }
      BasicNavigationExecutorSubsystem -up-|> BaseNavigationExecutorSubsystem
      class DummyNavigationExecutorSubsystem {
      }
      DummyNavigationExecutorSubsystem -up-|> BaseNavigationExecutorSubsystem
      namespace DriveExecutor {
        interface IDriveExecutorProcess #LimeGreen
        class TankDriveExecutorProcess #LimeGreen
        TankDriveExecutorProcess -up-|> IDriveExecutorProcess
      }
      namespace TrajectoryController {
        interface ITrajectoryControllerProcess
      }
      namespace TrajectorySelector {
        interface ITrajectorySelectorProcess
      }
    }
  }
}
@enduml