@startuml
title GlobalPlannerManager Process Class Diagram

namespace fast::fr {
  namespace messages {
  }
  namespace NavigationSystem {
    namespace GlobalPlannerSubsystem {
        interface IGlobalPlannerManagerProcess  {
          +{abstract} bool update(double current_time_sec, double delta_time_sec)
        }
        abstract BaseGlobalPlannerManagerProcess {
          +bool base_update(double current_time_sec, double delta_time_sec)

        }
        BaseGlobalPlannerManagerProcess -up-|> IGlobalPlannerManagerProcess
        class BasicGlobalPlannerManagerProcess {
          +bool update(double current_time_sec, double delta_time_sec)
        }
        BasicGlobalPlannerManagerProcess -up-|> BaseGlobalPlannerManagerProcess
        class DummyGlobalPlannerManagerProcess {
          +bool update(double current_time_sec, double delta_time_sec)
        }
        DummyGlobalPlannerManagerProcess -up-|> BaseGlobalPlannerManagerProcess
    }
  }
}
@enduml