' @compare_tag Process-ClassDiagram v0.1
@startuml
title FOVExtractor Process Class Diagram

namespace fast::rf {
  namespace DiagnosticDefinition {
    enum DiagnosticType
  }
  namespace messages {
    namespace InfrastructureMsgs {
      class DiagnosticMsg <<(M,#FFFF00)>>
      class ReadyToArmStatusMsg <<(M,#FFFF00)>>
    }
  }
  namespace core::Infrastructure {
    class DiagnosticManager
  }
  interface IProcess
  namespace PerceptionSystem {
    namespace DepthCameraPipelineSubsystem {
      package FOVExtractor #LightYellow;line:blue {

        interface IFOVExtractorProcess  {
          +{abstract} bool init()
        }
        IFOVExtractorProcess -up-|> IProcess
        abstract BaseFOVExtractorProcess {
          +DiagnosticMsg[] getDiagnostics()
          +bool updateDiagnostic(DiagnosticType type, Level level, DiagnosticMessage message, string description)
          +ReadyToArmStatusMsg get_ready_to_arm()
          #bool update(double current_time_sec)
          #string pretty()
          #DiagnosticManager m_diagnosticManager
          #ReadyToArmStatusMsg ready_to_arm

        }
        BaseFOVExtractorProcess .up.|> IFOVExtractorProcess
        BaseFOVExtractorProcess --> DiagnosticManager: <<use>>
        class BasicFOVExtractorProcessConfig {
          +bool is_ok()
          +string pretty()
        }
        class BasicFOVExtractorProcess {
          +bool init()
          +bool set_config(BasicFOVExtractorProcessConfig config)
          +bool update(double current_time_sec)
	  +string pretty()
          -BasicFOVExtractorProcessConfig config_
        }
        BasicFOVExtractorProcess -up-|> BaseFOVExtractorProcess
        BasicFOVExtractorProcess *-> BasicFOVExtractorProcessConfig: <<use>>
        class DummyFOVExtractorProcess {
          +bool update(double current_time_sec)
        }
        DummyFOVExtractorProcess -up-|> BaseFOVExtractorProcess
      }
    }
  }
}
@enduml
