@startuml
title Infrastructure Messages Package Diagram
namespace fast::rf {
  namespace DiagnosticDefinition {
    class DiagnosticType
    class DiagnosticMessage
  }

}
namespace fast::rf::messages {
  namespace InfrastructureMsgs  {
    class DiagnosticMsg <<(M,#FFFF00)>> #LimeGreen {
      +uint8_t systemID
      +uint8_t subsystemID
      +uint8_t processID
      +DiagnosticType diagnosticType
      +DiagnosticMessage diagnosticMessage
      +string description


    }
    DiagnosticMsg --> DiagnosticType: <<use>>
    DiagnosticMsg --> DiagnosticMessage: <<use>>
  }
}
@enduml