@startuml
title Infrastructure Messages Package Diagram
namespace fast::rf {
  enum Level
  namespace DiagnosticDefinition {
    enum DiagnosticType
    enum DiagnosticMessage
  }
  enum ArmedState

}
namespace fast::rf::messages {
  package InfrastructureMsgs #LightYellow;line:blue  {
    
    class ArmCommandMsg <<(M,#FFFF00)>> #LimeGreen {
      +ArmedState armed_state
    }
    ArmCommandMsg --> ArmedState: <<use>>
    struct ArmStateChangeSrvRequest #LimeGreen {
      +ArmedState requested_armed_state

    }
    ArmStateChangeSrvRequest --> ArmedState: <<use>>
    struct ArmStateChangeSrvResponse #LimeGreen {
      +ArmedState current_armed_state
      +bool request_approved

    }
    ArmStateChangeSrvResponse --> ArmedState: <<use>>
    class ArmStateChangeSrv <<(M,#FFFF00)>> #LimeGreen {
      +ArmStateChangeSrvRequest request
      +ArmStateChangeSrvResponse response
    }
    ArmStateChangeSrv +-- ArmStateChangeSrvRequest
    ArmStateChangeSrv +-- ArmStateChangeSrvResponse
    class ReadyToArmStatusMsg <<(M,#FFFF00)>> #LimeGreen {
      +uint8_t systemID
      +uint8_t subsystemID
      +uint8_t componentID
      +bool ready_to_arm
    }
    note right of ReadyToArmStatusMsg
    Implement during AB#1769
    end note
    class DiagnosticMsg <<(M,#FFFF00)>> #LimeGreen {
      +uint8_t systemID
      +uint8_t subsystemID
      +uint8_t processID
      +DiagnosticType diagnosticType
      +Level level
      +DiagnosticMessage diagnosticMessage
      +string description


    }
    DiagnosticMsg --> Level: <<use>>
    DiagnosticMsg --> DiagnosticType: <<use>>
    DiagnosticMsg --> DiagnosticMessage: <<use>>
  }
}
@enduml