@startuml
title Geometry Message Package Diagram

namespace fast::rf::messages {
  namespace Standard {
    class Covariance6DMsg <<(M,#FFFF00) >>
    class Vector3DMsg <<(M,#FFFF00) >>
  }

  namespace Geometry  {
    struct PointMsg <<(M,#FFFF00) >> #Orange {
      +double x
      +double y
      +double z 
    }
    struct OrientationMsg <<(M,#FFFF00) >> #Orange {
      +double roll
      +double pitch
      +double yaw
    }
    struct PoseMsg <<(M,#FFFF00)>> #Orange {
      +PointMsg position
      +OrientationMsg orientation

    }
    PoseMsg --> PointMsg: <<use>>
    PoseMsg --> OrientationMsg: <<use>>
    struct PoseWithCovarianceMsg <<(M,#FFFF00)>> #Orange {
      +PoseMsg pose
      +Covariance6DMsg covariance
    }
    PoseWithCovarianceMsg --> Covariance6DMsg: <<use>>
    PoseWithCovarianceMsg --> PoseMsg: <<use>>

    struct TwistMsg <<(M,#FFFF00)>> #Orange {
      +Vector3DMsg linear
      +Vector3DMsg angular
    }
    TwistMsg --> Vector3DMsg: <<use>>

    struct TwistWithCovarianceMsg <<(M,#FFFF00)>> #Orange {
      +TwistMsg twist
      +Covariance6DMsg covariance
    }
    TwistWithCovarianceMsg --> TwistMsg: <<use>>
    TwistWithCovarianceMsg --> Covariance6DMsg: <<use>>

    struct OdomMsg <<(M,#FFFF00)>> #Orange {
      +PoseWithCovarianceMsg pose
      +TwistWithCovarianceMsg twist
    }
    OdomMsg --> PoseWithCovarianceMsg: <<use>>
    OdomMsg --> TwistWithCovarianceMsg: <<use>>
  }
    
}
@enduml