@startuml
title RemoteControl Subsystem Class Diagram
namespace fast::rf {
  namespace UserInterfaceSystem {
    package RemoteControlSubsystem #LightYellow;line:blue  {
      interface IRemoteControlSubsystem {

      }
      abstract BaseRemoteControlSubsystem {

      }
      BaseRemoteControlSubsystem -up-|> IRemoteControlSubsystem
      class BasicRemoteControlSubsystem {
      }
      BasicRemoteControlSubsystem -up-|> BaseRemoteControlSubsystem
      class DummyRemoteControlSubsystem {
      }
      DummyRemoteControlSubsystem -up-|> BaseRemoteControlSubsystem
      package TeleopControlProcess #LimeGreen {
        interface ITeleopControlProcess #LimeGreen
        class BasicTeleopControlProcess #LimeGreen
        BasicTeleopControlProcess -up-|> ITeleopControlProcess
      }
    }
  }
}
@enduml