@startuml
title ArmedStateManager Process Class Diagram

namespace fast::rf {
  namespace DiagnosticDefinition {
    enum DiagnosticType
  }
  namespace messages {
    namespace InfrastructureMsgs {
      class DiagnosticMsg <<(M,#FFFF00)>>
      class ArmCommandMsg <<(M,#FFFF00)>>
      class ReadyToArmStatusMsg <<(M,#FFFF00)>> 
      struct ArmStateChangeSrvRequest
      struct ArmStateChangeSrvResponse
      class ArmStateChangeSrv <<(M,#FFFF00)>>  {
          +ArmStateChangeSrvRequest request
          +ArmStateChangeSrvResponse response
      }
      ArmStateChangeSrv +-- ArmStateChangeSrvRequest
      ArmStateChangeSrv +-- ArmStateChangeSrvResponse
    }
  }
  namespace core::Infrastructure {
    class DiagnosticManager
  }
  namespace SafetySystem {
    namespace ModeManagerSubsystem {
      package ArmedStateManager #LightYellow;line:blue {
        class ArmStateCommander #LimeGreen {
            +bool init()
            +string pretty()
            +bool update(double current_time_sec)
            +bool update_ready_to_arm(bool ready_to_arm)
            +ArmStateChangeSrvResponse request_armstate_change(ArmfChangeSrvRequest request)
            +ArmCommandMsg get_ArmCommandMsg()
        }
        struct Monitor #LimeGreen {
          +uint8 systemID
          +uint8 subsystemID
          +uint8 processID
          +MonitorKey key
          +bool ready_to_arm
          +double time_last_updated
          +uint64 rx_count
        }
        class ReadyToArmComputer #LimeGreen {
            
            +bool init()
            +bool set_config(uint8_t expected_ready_to_arm_signals)
            +string pretty()
            +bool update(double current_time_sec)
            +bool get_ready_to_arm()
            +bool new_ArmedStatus(ReadyToArmStatusMsg msg)
            +bool is_all_signals_rate_ok()
            +bool is_all_signals_ever_received()
            -bool add_monitor(fast::rf::messages::InfrastructureMsgs::ReadyToArmStatusMsg msg)
            -Monitor[] monitors
            -uint8 expected_ready_to_arm_signals_
        }
        ReadyToArmComputer +-- Monitor
        struct ArmedStateManagerProcessConfig {
          +uint8 expected_arm_signals
          +bool is_ok()
          +string pretty()
        }
        interface IArmedStateManagerProcess #LimeGreen {
          +{abstract} bool init()
          +{abstract} bool set_config(ArmedStateManagerProcessConfig config)
          +{abstract} DiagnosticMsg[] get_diagnostics()
          +{abstract} bool update(double current_time_sec)
          +{abstract} string pretty()
          +{abstract} ArmStateChangeSrvResponse request_armstate_change(ArmStateChangeSrvRequest request)
          +{abstract} bool new_ReadyToArmStatus(ReadyToArmStatusMsg msg)
          +{abstract} ArmCommandMsg get_ArmCommandMsg()
        }
        IArmedStateManagerProcess --> ArmedStateManagerProcessConfig: <<use>>
        abstract BaseArmedStateManagerProcess #LimeGreen {
          
          +DiagnosticMsg[] get_diagnostics()
          +bool get_ready_to_arm()
          #bool set_config(ArmedStateManagerProcessConfig config)
          #bool update(double current_time_sec)
          #string pretty()
          #DiagnosticManager diagnosticManager
          #ArmedStateManagerProcessConfig config_

        }
        BaseArmedStateManagerProcess .up.|> IArmedStateManagerProcess
        BaseArmedStateManagerProcess --> DiagnosticManager: <<use>>
        BaseArmedStateManagerProcess *-> ArmedStateManagerProcessConfig
        class ArmedStateManagerProcess #LimeGreen {
          +bool init()
          +set_config(ArmedStateManagerProcessConfig config)
          +bool update(double current_time_sec)
          +bool new_ReadyToArmStatus(ReadyToArmStatusMsg msg)
          +ArmStateChangeSrvResponse request_armstate_change(ArmfChangeSrvRequest request)
          +ArmCommandMsg get_ArmCommandMsg()
          -ArmStateCommander arm_state_commander
          -ReadyToArmComputer ready_to_arm_computer
        }
        ArmedStateManagerProcess -up-|> BaseArmedStateManagerProcess
        ArmedStateManagerProcess --> ArmStateCommander
        ArmedStateManagerProcess --> ReadyToArmComputer
        class DummyArmedStateManagerProcess  {
          +bool update(double current_time_sec)
        }
        DummyArmedStateManagerProcess -up-|> BaseArmedStateManagerProcess
      }
    }
  }
}
@enduml