@startuml
title Standard Messages Package Diagram

namespace fast::rf::messages {
  namespace StandardMsgs  {
    struct Vector3DMsg <<(M,#FFFF00) >> #Orange {
      +double x
      +double y
      +double z
    }
    struct Covariance3DMsg <<(M,#FFFF00) >> #Orange {
      +double[9] covariance
    }
    struct Covariance6DMsg <<(M,#FFFF00) >> #Orange {
      +double[36] covariance
    }
}
@enduml