---
config:
  layout: elk
  theme: base
  themeCSS: |
    .node rect { fill: rgba(30, 30, 46, 0.16) !important; stroke: #000000 !important; }
    .label { fill: #000000 !important; }

    .cssBoundary rect { fill: #ffffff !important; stroke: #000000 !important; }
    .cssBoundary .label { fill: #000000 !important; }

    .cssInvestigating rect { fill: #ffff00 !important; stroke: #000000 !important; }
    .cssInvestigating .label { fill: #000000 !important; }

    .cssDeveloping rect { fill: #ffab00 !important; stroke: #000000 !important; }
    .cssDeveloping .label { fill: #000000 !important; }

    .cssTrivialComplete rect { fill: #ffc0cb !important; stroke: #000000 !important; }
    .cssTrivialComplete .label { fill: #000000 !important; }

    .cssMinimalComplete rect { fill: #00ff00 !important; stroke: #000000 !important; }
    .cssMinimalComplete .label { fill: #000000 !important; }

    .cssFullyComplete rect { fill: #00ffff !important; stroke: #000000 !important; }
    .cssFullyComplete .label { fill: #000000 !important; }

    .cssSkipped rect { fill: #ff0000 !important; stroke: #000000 !important; }
    .cssSkipped .label { fill: #000000 !important; }

title: Mode Manager Subsystem Architecture
---
graph LR
    Inputs
    subgraph ArmedStateManager[Armed State Manager]
      ArmStateCommander[Arm State Commander]
      ReadyToArmComputer[Ready To Arm Computer]
    end
    Outputs

    Inputs --> |Arm State Change Service: Request| ArmedStateManager
    Inputs --> |Ready To Arm Status Message 1-N| ArmedStateManager

    ArmedStateManager --> |Arm Command| Outputs
    ArmedStateManager --> |Arm State Change Service: Response| Outputs


    class Inputs,Outputs cssBoundary
    class ArmedStateManager,ArmStateCommander,ReadyToArmComputer cssMinimalComplete