@startuml
title System-Pose Package Diagram

namespace fast::rf {
  namespace messages {
    class PoseMsg <<(M,#FFFF00) >>
  }
  namespace PoseSystem {
    together {
      namespace InertialSensorSubsystem {
        interface IInertialSensorSubsystem

      }
      namespace GlobalSensorSubsystem {
        interface IGlobalSensorSubsystem
      }
      namespace GlobalPoseSubsystem {
        interface IGlobalPoseSubsystem
      }
      namespace LocalPoseSubsystem {
        interface ILocalPoseSubsystem
      }
    }
    interface IPoseSystem #Orange {
      +{abstract} bool update(double current_time_sec, double delta_time_sec)
      +{abstract} PoseMsg get_global_pose()
      +{abstract} PoseMsg get_local_pose()
    }
    abstract BasePoseSystem #Orange {
      +PoseMsg get_global_pose()
      +PoseMsg get_local_pose()
      #bool base_update(doublecurrent_time_sec, double delta_time_sec)
      #double current_time_sec_
      #PoseMsg global_pose_
      #PoseMsg local_pose_
    }
    IPoseSystem <|-- BasePoseSystem
    class BasicPoseSystem {

    }
    BasePoseSystem <|-- BasicPoseSystem
    class DummyPoseSystem #Orange {
      +bool update(double current_time_sec, double delta_time_sec)
    }
    BasePoseSystem <|-- DummyPoseSystem
  }
}
@enduml