@startuml
title System-Pose Package Diagram

namespace fast::rf {
  namespace messages {
    namespace GeometryMsgs {
      class AccelMsg <<(M,#FFFF00)>>
      class OdomMsg <<(M,#FFFF00) >>
    }
    namespace SensorMsgs {
      class ImuMsg <<(M,#FFFF00) >>
    }
  }
  package PoseSystem #LightYellow;line:blue {
    namespace InertialSensorSubsystem #LimeGreen {
      interface IInertialSensorSubsystem #LimeGreen

    }
    namespace GlobalSensorSubsystem {
      interface IGlobalSensorSubsystem
    }
    namespace GlobalPoseSubsystem {
      interface IGlobalPoseSubsystem
    }
    namespace LocalPoseSubsystem #LimeGreen {
      interface IInertialSensorFuserProcess #LimeGreen {}
      class BasicInertialSensorFuserProcess #Pink {}
      BasicInertialSensorFuserProcess -up-|> IInertialSensorFuserProcess

      interface ILocalPoseFuserProcess #LimeGreen {}
      class BasicLocalPoseFuserProcess #Pink {}
      BasicLocalPoseFuserProcess -up-|> ILocalPoseFuserProcess
      
    }
    class PoseUtility #LimeGreen {
      +{static} bool differentiate(OdomMsg previous, OdomMsg current,AccelMsg computed_angular_acc)
    }

    interface IPoseSystem #Orange {
      +{abstract} bool update(double current_time_sec)
      +{abstract} OdomMsg get_global_pose()
      +{abstract} OdomMsg get_local_pose()
    }
    abstract BasePoseSystem #Orange {
      +OdomMsg get_global_pose()
      +OdomMsg get_local_pose()
      #bool base_update(doublecurrent_time_sec)
      #double current_time_sec_
      #OdomMsg global_pose_
      #OdomMsg local_pose_
    }
    IPoseSystem <|-- BasePoseSystem
    class BasicPoseSystem {

    }
    BasePoseSystem <|-- BasicPoseSystem
    class DummyPoseSystem #Orange {
      +bool update(double current_time_sec)
    }
    BasePoseSystem <|-- DummyPoseSystem
  }
}
@enduml