@startuml
title Logger Class Diagram
package fast::rf #LightYellow;line:blue {
    namespace messages::InfrastructureMsgs {
        class DiagnosticMsg <<(M,#FFFF00)>>
    }
    enum LoggerStatus #LimeGreen {
        UNKNOWN = 0,
        FAILED_TO_OPEN = 1,
        LOG_WRITTEN = 2,
        LOG_SUPPRESSED = 3,
        END_OF_LIST = 4
    }
    class Logger #LimeGreen {
        +Logger(Level level, std::string name)
        +logDiagnostic(DiagnosticMsg msg)
        +logDebug(string msg)
        +logInfo(string msg)
        +logNotice(string msg)
        +logWarn(string msg)
        +logError(string msg)
        +logFatal(string msg)
    }
    Logger +-- LoggerStatus
}
@enduml