@startuml
title Logger Class Diagram
package fast::rf #LightYellow;line:blue {
    namespace messages::InfrastructureMsgs {
        class DiagnosticMsg <<(M,#FFFF00)>>
    }
    enum LoggerStatus #LimeGreen {
        UNKNOWN = 0,
        FAILED_TO_OPEN = 1,
        LOG_WRITTEN = 2,
        LOG_SUPPRESSED = 3,
        END_OF_LIST = 4
    }
    class Logger #LimeGreen {
        +Logger(Level level, std::string name)
        +log_diagnostic(DiagnosticMsg msg)
        +log_debug(string msg)
        +log_info(string msg)
        +log_notice(string msg)
        +log_warn(string msg)
        +log_error(string msg)
        +log_fatal(string msg)
    }
    Logger +-- LoggerStatus
}
@enduml