@startuml
title Awareness Msg Class Diagram

namespace fast::rf::messages {
  namespace Geometry {
    class OdomMsg <<(M,#FFFF00) >>
  }
  namespace Awareness {
  
    class ObjectMsg <<(M,#FFFF00) >> {

    }
    ObjectMsg --> OdomMsg: <<use>>
    class ObjectsMsg <<(M,#FFFF00) >> {

    }
    ObjectsMsg --> ObjectMsg: <<use>>
    
  }
}
@enduml