@startuml
title System-Safety Package Diagram

namespace fast::rf {
  namespace messages  {}
  package SafetySystem #LightYellow;line:blue {
    interface ISafetySystem {
    }
    abstract BaseSafetySystem {
    }
    ISafetySystem <|-- BaseSafetySystem
    class BasicSafetySystem {

    }
    BaseSafetySystem <|-- BasicSafetySystem
    class DummySafetySystem  {
    }
    BaseSafetySystem <|-- DummySafetySystem
    namespace ModeManagerSubsystem #Yellow {
      interface IArmedStateManagerProcess #Yellow {

      }
      class BasicArmedStateManagerProcess #Yellow {
      }
      BasicArmedStateManagerProcess -up-|> IArmedStateManagerProcess
    }
  }
}
@enduml