@startuml
title System-UserInterface Package Diagram

namespace fast::rf {
  namespace messages  {}
  namespace UserInterfaceSystem {
    namespace Tools {
      class DiagnosticViewer {

      }
      class SystemViewer {

      }
    }
    package RemoteControlSubsystem #Yellow {

    } 
    
}
@enduml