@startuml
title BaseMachine Subsystem Class Diagram
namespace fast::rf {
  namespace messages {
  }
  namespace BaseMachineSystem {
    package BaseMachineSubsystem #LightYellow;line:blue  {
      interface IBaseMachineSubsystem {

      }
      abstract BaseBaseMachineSubsystem {

      }
      BaseBaseMachineSubsystem .up.|> IBaseMachineSubsystem
      class BasicBaseMachineSubsystem {
      }
      BasicBaseMachineSubsystem -up-|> BaseBaseMachineSubsystem
      class DummyBaseMachineSubsystem {
      }
      DummyBaseMachineSubsystem -up-|> BaseBaseMachineSubsystem
      interface IHatDriverProcess #LimeGreen
      class ServoHatDriverProcess #LimeGreen
      ServoHatDriverProcess -up-|> IHatDriverProcess
      class IServoHatDriver #LimeGreen
      class ServoDriver #LimeGreen
      ServoDriver -up-|> IServoHatDriver
      ServoHatDriverProcess --> IServoHatDriver: <<use>>

    }
  }
}
@enduml