---
config:
  layout: elk
  theme: base
  themeCSS: |
    .node rect { fill: rgba(30, 30, 46, 0.16) !important; stroke: #000000 !important; }
    .label { fill: #000000 !important; }

    .cssBoundary rect { fill: #ffffff !important; stroke: #000000 !important; }
    .cssBoundary .label { fill: #000000 !important; }

    .cssInvestigating rect { fill: #ffff00 !important; stroke: #000000 !important; }
    .cssInvestigating .label { fill: #000000 !important; }

    .cssDeveloping rect { fill: #ffab00 !important; stroke: #000000 !important; }
    .cssDeveloping .label { fill: #000000 !important; }

    .cssTrivialComplete rect { fill: #ffc0cb !important; stroke: #000000 !important; }
    .cssTrivialComplete .label { fill: #000000 !important; }

    .cssMinimalComplete rect { fill: #00ff00 !important; stroke: #000000 !important; }
    .cssMinimalComplete .label { fill: #000000 !important; }

    .cssFullyComplete rect { fill: #00ffff !important; stroke: #000000 !important; }
    .cssFullyComplete .label { fill: #000000 !important; }

    .cssSkipped rect { fill: #ff0000 !important; stroke: #000000 !important; }
    .cssSkipped .label { fill: #000000 !important; }

title: Pose System Architecture
---
graph LR
    Inputs
    GlobalSensorSubsystem[Global Sensor Subsystem]
    InertialSensorSubsystem[Inertial Sensor Subsystem]
    GlobalPoseSubsystem[Global Pose Subsystem]
    LocalPoseSubsystem[Local Pose Subsystem]
    Outputs

    Inputs --> |Wheel Odometry| LocalPoseSubsystem
    Inputs --> |Visual Odometry| LocalPoseSubsystem
    
    GlobalSensorSubsystem --> |GPS Sensor Data 1-N | GlobalPoseSubsystem
    
    InertialSensorSubsystem --> LocalPoseSubsystem

    LocalPoseSubsystem --> |Local Pose | GlobalPoseSubsystem
    LocalPoseSubsystem --> |Local Odometry| Outputs

    GlobalPoseSubsystem --> |Global Odometry| Outputs

    class Inputs,Outputs cssBoundary