' @compare_tag Process-ClassDiagram v0.1
@startuml
title ModeManager Subsystem Class Diagram
namespace fast::rf {
  namespace messages {
  }
  namespace SafetySystem {
    package ModeManagerSubsystem #LightYellow;line:blue {
      interface IModeManagerSubsystem {

      }
      abstract BaseModeManagerSubsystem {

      }
      BaseModeManagerSubsystem .up.|> IModeManagerSubsystem
      class BasicModeManagerSubsystem {
      }
      BasicModeManagerSubsystem -up-|> BaseModeManagerSubsystem
      class DummyModeManagerSubsystem {
      }
      DummyModeManagerSubsystem -up-|> BaseModeManagerSubsystem
      namespace ArmedStateManager {
        interface IArmedStateManagerProcess #LimeGreen {

        }
        class ArmedStateManagerProcess #LimeGreen {
        }
        ArmedStateManagerProcess -up-|> IArmedStateManagerProcess
      }
    }
  }
}
@enduml
