@startuml
title DepthCamera Sensor Fuser Sequence Diagram
actor Sensor as sensor
participant Process as process
participant Combiner as combiner
participant OverlapRemover as overlapRemover
participant NoiseReducer as noiseReducer

alt Initialize
process++
process -> combiner++: init()
combiner --> process--: status
process -> overlapRemover++: init()
overlapRemover --> process--: status
process -> noiseReducer++: init()
noiseReducer --> process--: status
end

alt Executive
end
@enduml