@startuml
title Sensor Message Package Diagram

namespace fast::rf::messages {
  namespace StandardMsgs {
    class Covariance3DMsg <<(M,#FFFF00) >>
    class Vector3DMsg <<(M,#FFFF00)>>
  }
  namespace GeometryMsgs {
    class OrientationMsg <<(M,#FFFF00) >>
  }
  package SensorMsgs #LightYellow;line:blue {
    GlobalPositionCovarianceMsg --> Covariance3DMsg: <<use>>
    struct GlobalPositionSensorMsg <<(M,#FFFF00)>> #LimeGreen {
      +double time_stamp
      +double latitude_deg
      +double longitude_deg
      +double altitude_m
      +uint16_t satellites
      +Covariance3DMsg covariance
      +bool ok()
    }
    GlobalPositionSensorMsg --> Covariance3DMsg: <<use>>

    struct JoyMsg <<(M,#FFFF00)>> #LimeGreen {
      +double time_stamp
      +double[] axes
      +uint32[] buttons
    }

    struct ImuMsg <<(M,#FFFF00)>> #Yellow {
      +double time_stamp
      +uint64 seq
      +OrientationMsg orientation
      +Covariance3DMsg orientation_covariance
      +Vector3DMsg angular_velocity
      +Covariance3DMsg angular_velocity_covariance
      +Vector3DMsg linear_acceleration
      +Covariance3DMsg linear_acceleration_covariance
      +string pretty()
    }
    ImuMsg --> OrientationMsg: <<use>>
    ImuMsg --> Vector3DMsg: <<use>>
    ImuMsg --> Covariance3DMsg: <<use>>
  }
  @enduml