---
# @compare_tag Subsystem-MermaidArchitecture v0.1
config:
  layout: elk
  theme: base
  themeCSS: |
    .node rect { fill: rgba(30, 30, 46, 0.16) !important; stroke: #000000 !important; }
    .label { fill: #000000 !important; }

    .cssBoundary rect { fill: #ffffff !important; stroke: #000000 !important; }
    .cssBoundary .label { fill: #000000 !important; }

    .cssInvestigating rect { fill: #ffff00 !important; stroke: #000000 !important; }
    .cssInvestigating .label { fill: #000000 !important; }

    .cssDeveloping rect { fill: #ffab00 !important; stroke: #000000 !important; }
    .cssDeveloping .label { fill: #000000 !important; }

    .cssTrivialComplete rect { fill: #ffc0cb !important; stroke: #000000 !important; }
    .cssTrivialComplete .label { fill: #000000 !important; }

    .cssMinimalComplete rect { fill: #00ff00 !important; stroke: #000000 !important; }
    .cssMinimalComplete .label { fill: #000000 !important; }

    .cssFullyComplete rect { fill: #00ffff !important; stroke: #000000 !important; }
    .cssFullyComplete .label { fill: #000000 !important; }

    .cssSkipped rect { fill: #ff0000 !important; stroke: #000000 !important; }
    .cssSkipped .label { fill: #000000 !important; }

title: Inertial Sensor Subsystem Architecture
---
graph LR
    subgraph IMUProcess1[IMU Process 1]
      IMUDriver1[IMU Driver]
    end
    subgraph IMUProcess2[IMU Process 2]
      IMUDriver2[IMU Driver]
    end
    subgraph IMUProcessN[IMU Process N]
      IMUDriverN[IMU Driver]
    end
    Outputs

    IMUProcess1 --> |IMU Data 1| Outputs
    IMUProcess2 --> |IMU Data 2| Outputs
    IMUProcessN --> |IMU Data N| Outputs

    class Inputs,Outputs cssBoundary
    class IMUProcess1,IMUDriver1,IMUProcess2,IMUDriver2,IMUProcessN,IMUDriverN cssMinimalComplete
