@startuml
title System-Terrain Package Diagram

namespace fast::rf {
  package TerrainSystem #LightYellow;line:blue {
    interface ITerrainSystem {
    }
    abstract BaseTerrainSystem {
    }
    ITerrainSystem <|-- BaseTerrainSystem
    class BasicTerrainSystem {

    }
    BaseTerrainSystem <|-- BasicTerrainSystem
    class DummyTerrainSystem  {
    }
    BaseTerrainSystem <|-- DummyTerrainSystem
  }
}
@enduml