name: Build and Test CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: ./scripts/setup_robot.sh

      - name: Prepare to Build
        run: cmake -S . -B build

      - name: Build Repo
        run: cmake --build build --target install -j20

      - name: Run Unit Tests
        run: ctest --verbose
        working-directory: build

      - name: Generate Cobertura XML
        run: |
          pip install gcovr
          gcovr --xml-pretty -o coverage.xml .
