name: SonarQube C++ Analysis with Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_scan:
    name: Build, Test, and Scan
    runs-on: ubuntu-latest

    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper logs will be placed

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones must be disabled for a relevance of analysis

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential gcovr

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          # Optional: projectBaseDir defaults to '.' if left out
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
